### PR TITLE
v3: Remove node  < 18 from CI matrix

### PR DESCRIPTION
**Pull request by broofa**
Putting this up so we have something to look at for #115.  Cutoff does not have to be at node@16.  That's just where we'd draw the line in the world of `uuid`.

Maybe create a v3 branch / milestone for this and the `peerDependency` change (if/when that happens), and the mime-score PR (coming soon)?

### CODE REVIEW

**Comment by broofa** [comment]
Should the `io.js` platforms be removed as well?

**Comment by dougwilson** [comment]
> Should the io.js platforms be removed as well?

Yes, especially them. They give trouble every so often I want them gone 100% in the next major lol

**Comment by dougwilson** [comment]
Just checking in as this is not forgotten. Will finalize once the Express versions are hammered down so we know this is usable in Express.

**Comment by wesleytodd** [comment]
We have moved to drop up to node 18 for express. @broofa I pushed that change, as well as adding node 22 here. Also re-targeting this to a new 3.x branch.

**Pull request merged**
