### PR TITLE
Create index.d.ts

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by dougwilson** [comment]
We need a way yo test this in the CI to ensure correctness in an ongoing way. Otherwise there is no value having it here over somewhere like definitely typed project.

**Comment by wcandillon** [comment]
@dougwilson In typescript 2.0 it looks up for index.d.ts by default to find the typing of a package. But I agree that some testing would be nice.

**Comment by dougwilson** [comment]
Sure, but I mean there is no point of adding a file to the project if no one running it understands typescript to maintain the file and there is no testing in the CI for anyone to even know when the file becomes incorrect. I don't know typescript even to even know if this file is correct to even merge, as well.

**Comment by Borewit** [comment]
I probably should have continued on your pull request [wcandillon](https://github.com/wcandillon)
The `declare module "mime-types"` should not be included if you place the Typing definition directly in the module. You only do this to declare an external module you import, and that is probably how you started. 
Been there, done that myself.

Maybe you can review [my pull request](https://github.com/jshttp/mime-types/pull/30) and check if it working for you.

To install as NPM directly, you may use: `npm install git+https://github.com/Borewit/mime-types.git#TypeScriptDefinitions`

**Comment by dougwilson** [comment]
I'm probably just going to pass on accepting the typing file altogether, then, based on previous discussions in the organization. Thanks for the effort, though! I wish we understood TypeScript to even be able to review the PR for correctness and maintain it for the future, but there isn't really any interest in TypeScript within the organization currently. I'm not sure how to overcome that hump, if you have suggestions.

**Pull request closed without merging**
