### PR TITLE
Remove dependency from "path" module

### PR DESCRIPTION
**Pull request by CleyFaye**
Hi,

For a React-Native project, we had to remove the dependency to require("path").extname in mime-types.
To do so we just cloned the extname() function from node. Since it might be useful, I'm proposing a PR for that.

### CODE REVIEW

**Comment by dougwilson** [comment]
Thank you, but we're not interested in maintaining a complete copy of third-party code. If there is another method that does not involve copying it into this repo, I'm open to hear it; the purpose of dependencies is to prevent the need to copy and paste code into repos these days. I'm not familiar with React-Native, but this is a Node.js project, and the `path` module is part of Node.js itself: https://nodejs.org/dist/latest-v13.x/docs/api/path.html

**Comment by CleyFaye** [comment]
Ok, thought so.
The only "sane" approach that comes to mind would be to have another dependency that mangage these differences, but I'm not sure it would provide a significant advantage for most users of this library.
We'll just keep our fork up to date.

Thanks,

**Comment by CleyFaye** [comment]
Another, maybe "cleaner" option would be to move the functions in a closure where extname is dynamically provided; that's the approach I finally used.
This way, I stay "compatible" with the default behavior of using path in index.js, but apps on other engines can instantiate a different set of functions with custom implementation of extname.

This, also, might be a bit overkill for the initial scope of this library, but that's another viable approach to this non-issue.

**Comment by hayond** [comment]
@CleyFaye same problem in react-native，i finally have to copy this repo to local ^_^

**Pull request closed without merging**
