### PR TITLE
Browserify

### PR DESCRIPTION
**Pull request by stropitek**
I find this library useful in the browser as well.

I'm using [browserify](http://browserify.org/) to build it and everything seems to work.  I used [mochify](https://github.com/mantoni/mochify.js) to execute the test suite and it's all green.

The "mime-types" name is still available on [bower](http://bower.io/)

### CODE REVIEW

**Comment by dougwilson** [comment]
Thank you! Sorry for my ignorance on `bower` ( :) ), but if there a way we can not check in machine-generated files (like the `browser/` directory) to GitHub? How do I publish a module to `bower`? Also, if you get a change, please take a look into the failing Travis CI tests :)

**Comment by stropitek** [comment]
I've removed the machine-generated files. To generate them you need recent version of node (I think >=0.10.0), then
```
  npm install -g gulp
  npm run browserify
```

I've actually never published to bower but I think
```bower register mime-types git://github.com/jshttp/mime-types.git``` and that's it

**Comment by stropitek** [comment]
I'm not sure how bower could build the files if you don't want them in the repo. I'll check that tomorrow.

**Comment by dougwilson** [comment]
Cool :) So if we really have to have them in our repo, I suppose, but it would at least be good to know if it's possible not. The main reason that we can forget to rebuild them on every commit by accident.

If we do have to include them, since the source becomes part of our repo, we would need to know all the copyrights and full text licenses for all the included source (it looks like third-party code gets checked in) for legal reasons.

As for optionalDependencies, you cannot add gulp and friends there, as that is for end users, so suddenly installing this module from npm will try to install gulp and stuff on everyone's machine.

**Comment by stropitek** [comment]
So it's not possible to not have them in the repo, since bower only stores the the git url and there isn't a way to a build with bower. I've seen that [bluebird](https://github.com/petkaantonov/bluebird) keeps the releases that contain the built files outside of the master branch. Other repos don't bother. Others like [superagent](https://github.com/visionmedia/superagent) consider the end-user has to browserify himself.

For the copyright stuff I don't really understand, I don't think third party code will be included in the final source code (unless generated code is considered as such?) I'm not sure I understand what you meant... Would it be ok now that I've remove the gulp dependencies?

I've remove the optionalDependencies. But I had to do a npm install of browserify and uglifyjs inside in npm scripts because I cannot add them to the dev dependencies otherwise travis CI tests will fail for node < 0.10. It's not very nice but I don't see any other way to do it.

**Comment by dougwilson** [comment]
> I've seen that bluebird keeps the releases that contain the built files outside of the master branch. 

That sounds reasonable. How can we achieve this :)? Any special thing you have to do to publish to `bower` so it knows to look in a certain branch?

> For the copyright stuff I don't really understand, I don't think third party code will be included in the final source code (unless generated code is considered as such?) I'm not sure I understand what you meant...

So you used to have the file https://github.com/stropitek/mime-types/blob/master/dist/mime-types.js checked into this changeset. If you look at it, it contains source code from outside this repository. The first bit shows it's "Copyright Joyent, Inc. and other Node contributors." and include the license. There are other parts of code that is in there that is not from this repo and doesn't include the full license text, so that's ultimately the issue with us checking that file into this repo, as it constitutes "redistribution" and I don't know if I'm allowed to redistribute the code without seeing the license.

**Comment by stropitek** [comment]
Oh yes I missed that. Browserify includes some code from [this file](https://github.com/joyent/node/blob/master/lib/path.js) because he has detected ```require('path')``` in your code. Since ```path``` has a dependency on ```process``` a second part is added that fakes ```process```. I suppose it's this second part that your refer as to "other parts of code". This second part is actually not needed so it can be removed by calling browserify with the ```--detect-globals``` options set to ```false```.
>That sounds reasonable. How can we achieve this :)? Any special thing you have to do to publish to ```bower``` so it knows to look in a certain branch?

For example after publishing to npm you would:
* create a local branch for example v2.1.2
* Set ```version``` in ```bower.json``` to ```2.1.2```
* Build browser files with ```npm run build```
* Commit and create a new tag that you name 2.1.2
* Push the tag to github (no need to push the branch)

The bower package needs to be registered once but doesn't need to be published. To use your library bower users will need to specify the name of the package and optionally a version. Bower will then fetch the appropriate tag from github and copy what is needed.

**Comment by dougwilson** [comment]
Hm... well, we are only tagging the commits that are the exact one that was published to `npm`, so if `bower` goes of git tags, then that won't work, as our tags would be on `master`, rather than a second branch. It seems to be that `bower` is way too closely tied to the layout and management of a git repo. This means that, really, the `bower` `mime-types` module should actually be a seperate repo.

**Comment by stropitek** [comment]
You could always publish to ```npm``` the tagged version with the browserified files. That's actually what bluebird does.

**Comment by dougwilson** [comment]
But the problem with that is we let your dependency's version float, but then the browserified copy, since it will contain the dependencies embedded, will of course not float, as it will be fixed as publish time. This means that installing this module you'll end up with a different MIME database depending on if you are using the browserified version or not (and also means we'd have to publish for every dependency update).

**Comment by dougwilson** [comment]
But even then, I don't see how publishing the browserified files will help with bower?

**Comment by dougwilson** [comment]
So I was reading about bower and talking about it with a coworker and there is no requirement at all for us to store any kind of browserified file here, as bower does not carer at all and you can always use browserify on your installed bower_components after the fact if you need to do that.

**Comment by dougwilson** [comment]
We either have to figure out how to get this module's dependencies on bower and then put this module on bower without bundling dependencies, or a bower version of this module needs to be a separate repo, since bower only works off the literal contents of the repos and our tags only point to the exact commits that are what was published to npm.

Can you help me determine how bower with with dependencies?

**Comment by dougwilson** [comment]
Hi @stropitek , any help with my last question?

**Comment by stropitek** [comment]
I cannot see how to make it work using bower dependencies. Mime-db does not need to be built and could be added as is to bower, and mime-types could have it as a dependency. But how should the browserified version of mime-types know how to load that dependency?

The idea of a separate repo that bundles everything together seems easier and more maintainable to me, as long as it is a bot that updates the project every time it (or one of it's dependencies) is bumped. Since this repo does not have complex nested dependencies, that seems manageable...

Maybe there are some pitfalls I cannot see with that approach since I've never seen it used in any other project. If we go with that I also don't know how the repo should be versioned since it would need to be bumped more often than the original mime-types repo.

PS: I will probably we slow to respond until I get my computer replaced at home :smile:

**Comment by dougwilson** [comment]
Just install this module using `npm` and in a file you end up running through your browserify command, `require('mime-types')` somewhere and browserify will automatically bundle this module and it's dependency, without adding any additional dependencies to this repository.

**Pull request closed without merging**
