### PR TITLE
support filepaths to .contentType()

### PR DESCRIPTION
**Pull request by stephenplusplus**
I noticed the readme makes it seem as though file paths will please the .contentType() method, but when used with a path like "here/is/my/file.json", the directory separator `/` is being mistaken for a content-type's `/`, which is interpreted as "I don't need you to lookup the content-type". Instead of looking for a `/`, I changed it look for a `;`. Hope this isn't a terrible solution!

### CODE REVIEW

**Comment by dougwilson** [comment]
As long as `.contentType()` supports an actual MIME type, we really cannot add more ambiguity here. Just think you want to set your content type to the type `application/vnd.apache.thrift.json` ... we cannot tell what you want to do.

**Comment by dougwilson** [comment]
I still need to revive the `set-type` lib, but I don't see a good reason not to just use `path.extname`. I added an example to the README for this.

**Comment by stephenplusplus** [comment]
The only reason I thought this was supported in the first place was the second example in the readme (https://github.com/jshttp/mime-types/blob/master/README.md#mimecontenttypetype):

```js
mime.contentType('file.json') // 'application/json; charset=utf-8'
```

When I saw that, I thought "that makes so much sense!" That's my most common use case. I don't know why getting back what you give it is a more common one, but regardless, I'll continue to be a happy user of the library. Thanks!

**Comment by dougwilson** [comment]
Right. This is one reason I don't particularly like functions that behave differently depending on their argument. Ideally we would have a CT function that takes a type and a different CT function that takes file paths.

**Pull request closed without merging**
